# This file is parsed by Slab Zama's CI bot to handle AWS EC2 resources.
[profile.m6i]
region = "eu-west-3"
image_id = "ami-0be33931bc16f7a85"
instance_type = "m6i.metal"
subnet_id = "subnet-a029b7ed"
security_group= ["sg-0bf1c1d79c97bc88f", ]

[backend.aws.m6i]
region = "eu-west-3"
image_id = "ami-0be33931bc16f7a85"
instance_type = "m6i.metal"
subnet_id = "subnet-a029b7ed"
security_group= ["sg-0bf1c1d79c97bc88f", ]

[backend.aws.weekly_ciprofile]
region = "eu-west-3"
image_id = "ami-0be33931bc16f7a85"
instance_type = "c6i.24xlarge"
subnet_id = "subnet-a029b7ed"
security_group= ["sg-0bf1c1d79c97bc88f", ]

[backend.aws.pr_ciprofile]
region = "eu-west-3"
image_id = "ami-0be33931bc16f7a85"
instance_type = "c5.4xlarge"
subnet_id = "subnet-a029b7ed"
security_group= ["sg-0bf1c1d79c97bc88f", ]

[backend.aws.gpu_ciprofile]
region = "us-east-1"
image_id = "ami-0c2e815dbef0da3a2"
instance_type = "g4dn.4xlarge"

[backend.aws.big-cpu]
region = "eu-west-1"
image_id = "ami-0898af27b3e2421d8"
instance_type = "hpc7a.96xlarge"

[backend.aws.a10gpu]
region = "eu-west-1"
image_id = "ami-0898af27b3e2421d8"
instance_type = "g5.xlarge"

[backend.hyperstack.single-h100]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R535 CUDA 12.2"
flavor_name = "n3-H100x1"

[backend.hyperstack.8xh100]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R535 CUDA 12.2"
flavor_name = "n3-H100x8-NVLink"

[backend.hyperstack.l40_fallback]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R535 CUDA 12.2"
flavor_name = "n3-RTX-A600x1"
user = "ubuntu"

# Trigger benchmarks.
[command.bench]
workflow = "single_benchmark.yaml"
profile = "m6i"
