name: Check GitHub Issues
on:
  workflow_dispatch:

  schedule:
    - cron: "0 11 * * *"


env:
  ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  # Add event_name in the group as workflow dispatch means we could run this in addition to other
  # workflows already running on a PR or a merge e.g.
  group: "${{ github.ref }}-${{ github.event_name }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  check-github-actions:
    name: Check GitHub Issues
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Install dependencies
        id: install-deps
        run: |
          sudo ./script/make_utils/setup_os_deps.sh

      - name: Check GitHub actions
        run: |
          if [[ "${{ github.repository }}" == "concrete-ml-internal"  ]];then
            make check_issues
          fi

      - name: Slack Notification
        if: ${{ always() && !success() }}
        continue-on-error: true
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_ICON: https://pbs.twimg.com/profile_images/1274014582265298945/OjBKP9kn_400x400.png
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE:
            "Some 'FIXME: url' issues are present in the code base but closed on github\
            (${{ env.ACTION_RUN_URL }})"
          SLACK_USERNAME: ${{ secrets.BOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
